version: "3.7"

services:
  totaltube-conversion:
    image: docker.io/sersh/totaltube-conversion
    container_name: totaltube-conversion
    restart: always
    network_mode: host
    logging:
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      - TOTALTUBE_CONVERSION_PORT=9099
      - TOTALTUBE_CONVERSION_API_KEY=your-api-key
      - TOTALTUBE_CONVERSION_PATH=/data