version: "3.7"

services:
  totaltube-conversion:
    image: sersh/totaltube-conversion
    container_name: totaltube-conversion
    logging:
      options:
        max-size: "200k"
        max-file: "5"
    ports:
      - "8081:8080"
    environment:
      - TOTALTUBE_CONVERSION_API_KEY=some-api-key
      - TOTALTUBE_CONVERSION_PATH=/data